fix arm64 build

diff --git a/.otp-ci.yml b/.otp-ci.yml
--- a/.otp-ci.yml
+++ b/.otp-ci.yml
@@ -23,7 +23,7 @@ base-image-ubuntu-x86:
       ENV DEBIAN_FRONTEND=noninteractive
       ENV LANG=C.UTF-8
       ENV LC_ALL=C.UTF-8
-      RUN apt-get update && apt-get -y upgrade && apt-get install -y build-essential m4 autoconf fop xsltproc clang clang-format default-jdk libxml2-utils zlib1g-dev libncurses5-dev libssl-dev unixodbc-dev libgmp3-dev libwxbase3.0-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libsctp-dev lksctp-tools
+      RUN apt-get update && apt-get -y upgrade && apt-get install -y git build-essential m4 autoconf fop xsltproc clang clang-format default-jdk libxml2-utils zlib1g-dev libncurses5-dev libssl-dev unixodbc-dev libgmp3-dev libwxbase3.0-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libsctp-dev lksctp-tools
       RUN update-alternatives --set wx-config /usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.0" >  Dockerfile
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker build -t $UBUNTU_IMAGE:latest .
@@ -44,14 +44,13 @@ base-image-ubuntu-arm64:
       ENV DEBIAN_FRONTEND=noninteractive
       ENV LANG=C.UTF-8
       ENV LC_ALL=C.UTF-8
-      RUN apt-get update && apt-get -y upgrade && apt-get install -y build-essential m4 autoconf fop xsltproc clang clang-format default-jdk libxml2-utils zlib1g-dev libncurses5-dev libssl-dev unixodbc-dev libgmp3-dev libwxbase3.0-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libsctp-dev lksctp-tools
-      RUN update-alternatives --set wx-config /usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.0" >  Dockerfile
+      RUN apt-get update && apt-get -y upgrade && apt-get install -y git build-essential m4 autoconf fop xsltproc clang clang-format default-jdk libxml2-utils zlib1g-dev libncurses5-dev libssl-dev unixodbc-dev libgmp3-dev libwxbase3.0-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libsctp-dev lksctp-tools
+      RUN update-alternatives --set wx-config /usr/lib/aarch64-linux-gnu/wx/config/gtk3-unicode-3.0" >  Dockerfile
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker build --platform linux/arm64/v8 -t $UBUNTU_IMAGE_ARM64:latest .
     - docker push $UBUNTU_IMAGE_ARM64:latest
 
 build-ubuntu:
-  when: manual
   image: $UBUNTU_IMAGE:latest
   tags:
     - linux
@@ -73,8 +72,29 @@ build-ubuntu:
       - "release/"
     expire_in: 1 week
 
+build-ubuntu-arm64:
+  image: $UBUNTU_IMAGE_ARM64:latest
+  tags:
+    - linux
+  stage: build
+  script:
+    - export MAKEFLAGS="-j$(($(nproc) + 2))" ERLC_USE_SERVER=yes CC=clang CXX=clang++ CFLAGS="-O2 -g -Werror"
+    - export ERL_TOP=`pwd`
+    # install OTP into release/otp
+    - ./configure --with-ssl --with-ssl-lib-subdir=lib/aarch64-linux-gnu --prefix=$ERL_TOP/release/otp --disable-jit
+    - make
+    # Disable -Werror as testcases do not compile with it on
+    - export CFLAGS="-O2 -g"
+    - make tests
+    - make install
+    - cd release/tests/test_server
+    - $ERL_TOP/release/otp/bin/erl -noshell -eval "ts:install(),erlang:halt()."
+  artifacts:
+    paths:
+      - "release/"
+    expire_in: 1 week
+
 static-analysis-ubuntu:
-  when: manual
   tags:
     - linux
   needs:
@@ -98,7 +118,6 @@ static-analysis-ubuntu:
     - scripts/otp_html_check $ERL_TOP/release/otp/lib/erlang doc/index.html
 
 test-ubuntu-emulator:
-  when: manual
   tags:
     - linux
   dependencies:
@@ -120,9 +139,30 @@ test-ubuntu-emulator:
         - release/tests/test_server/ct_run.*/junit_report.xml
     expire_in: 1 week
 
+test-ubuntu-emulator-arm64:
+  tags:
+    - linux
+  dependencies:
+    - build-ubuntu-arm64
+  image: $UBUNTU_IMAGE_ARM64:latest
+  stage: test
+  script:
+    # Do not set -Werror, or tests will fail in hardly debuggable way
+    - export MAKEFLAGS="-j$(($(nproc) + 2))" ERLC_USE_SERVER=yes CC=clang CXX=clang++ CFLAGS="-O2 -g"
+    - export ERL_TOP=`pwd`
+    - cd release/tests/test_server
+    - $ERL_TOP/release/otp/bin/ct_run -dir $ERL_TOP/release/tests/emulator_test -ct_hooks cth_surefire [] -noshell -pa $ERL_TOP/release/tests/test_server
+  artifacts:
+    when: always
+    paths:
+      - release/tests/test_server/**
+    reports:
+      junit:
+        - release/tests/test_server/ct_run.*/junit_report.xml
+    expire_in: 1 week
+
 # This job is designed to be executed for Continuous Runs, testing all applications
 test-ubuntu-libs:
-  when: manual
   tags:
     - linux
   dependencies:
@@ -154,7 +194,6 @@ test-ubuntu-libs:
     expire_in: 1 week
 
 build-freebsd:
-  when: manual
   tags:
     - freebsd
   stage: build
@@ -175,7 +214,6 @@ build-freebsd:
     expire_in: 1 week
 
 test-freebsd-emulator:
-  when: manual
   tags:
     - freebsd
   stage: test
@@ -198,7 +236,6 @@ test-freebsd-emulator:
 
 # This job is designed to be executed for Continuous Runs, testing all applications
 test-freebsd-libs:
-  when: manual
   tags:
     - freebsd
   dependencies:
